[package]
authors = ["Doug Goldstein <cardoe@cardoe.com>"]
categories = ["command-line-utilities"]
description = "Generates a BitBake recipe for a package utilizing meta-rust's classes."
documentation = "https://github.com/cardoe/cargo-bitbake"
homepage = "https://github.com/cardoe/cargo-bitbake"
keywords = ["cargo-subcommand", "bitbake", "yocto", "recipe"]
license = "MIT/Apache-2.0"
edition = "2018"
name = "cargo-bitbake"
readme = "README.md"
repository = "https://github.com/cardoe/cargo-bitbake"
version = "0.3.16-alpha.0"

[badges]
is-it-maintained-issue-resolution = { repository = "cardoe/cargo-bitbake" }
is-it-maintained-open-issues = { repository = "cardoe/cargo-bitbake" }
maintenance = { status = "passively-maintained" }

[badges.travis-ci]
repository = "cardoe/cargo-bitbake"

[dependencies]
anyhow = "^1.0"
cargo = "^0.61"
git2 = "0.14"
itertools = "^0.10"
lazy_static = "^1"
md5 = "^0.7"
regex = "^1"
structopt = "^0.3"
